config/routes.rb
Mug6470::Application.routes.draw do

  resources :tutorials, :only => [:index, :show] do
    resources :sections, :only => [:index, :show]
  end

  resources :projects do
    resources :trials
  end

  resources :trials, :only => [:destroy]

  resources :data, :except => [:destroy, :update, :edit, :new] do
    collection do
      get :choose
      get :tweet
    end
  end

  resources :classifiers, :except => [:destroy, :update, :edit, :create, :new] do 
    collection do
      get :choose
    end
  end

  resource :session, :controller => 'session' do
    collection do
      get :about
    end
  end
  
  resources :users, :only => [:new, :create] do
    collection do
      post :check_email
    end
  end
  
  match 'projects/trials' => 'trials#create'

  root :to => 'session#show'

end

app/controllers/session_controller.rb
# Manages logging in and out of the application.
class SessionController < ApplicationController
  include Authpwn::SessionController
  
  # Sets up the 'session/welcome' view. No user is logged in.
  def welcome
    # You can brag about some statistics.
    @user_count = User.count
  end
  private :welcome

  # Sets up the 'session/home' view. A user is logged in.
  def home
    redirect_to tutorials_url
  end
  private :home
  
  # Sets up the 'session/about' view.
  def about
  end
  
  # The notification text displayed when a session authentication fails.
  def bounce_notice_text(reason)
    case reason
    when :invalid
      'Invalid e-mail or password'
    when :blocked
      'Account blocked. Please verify your e-mail address'
    end
  end
  
  # You shouldn't extend the session controller, so you can benefit from future
  # features, like Facebook / Twitter / OpenID integration. But, if you must,
  # you can do it here.
end

app/views/session/about.html.erb
<article class="main">
  <section>
    <h2>About ProtoM</h2>
    <p>
      ProtoM is built on top of <%= link_to 'Weka', 'http://www.cs.waikato.ac.nz/ml/weka/'%>, 
      an open source platform for machine learning and data mining built at the University of Waikato.
      For more information, please visit the Weka
      <%= link_to 'download page', 'http://www.cs.waikato.ac.nz/ml/weka/index_downloading.html'%>
      or read the original paper:
    </p>
    <p>
      Mark Hall, Eibe Frank, Geoffrey Holmes, Bernhard Pfahringer, Peter Reutemann, Ian H. Witten (2009); The WEKA Data Mining Software: An Update; SIGKDD Explorations, Volume 11, Issue 1.
    </p>
    <a href="http://www.cs.waikato.ac.nz/ml/weka/"><%= image_tag 'weka-logo.png', :id => 'weka-image' %></a>
  </section>
  <section>
    <h3>ARFF data format</h3>
    <p>
      To upload your own data sets to ProtoM, you need to format your data files 
      according to WEKA's <a href="http://weka.wikispaces.com/ARFF">ARFF</a> 
      data format, with '.arff' as the file extension. The first attribute of 
      the relation has to be ID numeric.
    </p>
    <p>
      You can find an example of a valid ARFF file 
      <%= link_to 'here', '/tweet-sentiment-example.arff' %>.
  </section>
</article>
<article class="sidebar">
  <h2>Contact</h2>
  <p>
    For any questions, requests or comments, please contact us at <a href="mailto:protom.web@gmail.com">protom.web@gmail.com</a>
  </p>
</article>  

app/views/session/forbidden.html.erb
<p>
  This view gets displayed when the user tries to access something forbidden.
</p>

<% if current_user %>
<p>
  You should inform the user that they are logged in as
  <%= current_user.exuid %> and suggest them to
  <%= link_to 'Log out', session_path, :method => :destroy %> and log in as a
  different user.  
</p>
<% else %>
<p>
  The user will only see this if JavaScript is disabled. Ask them to
  <%= link_to 'Log in', new_session_path %>.
</p>
<script type="text/javascript">
window.location = "<%= new_session_path %>";
</script>
<% end %>

app/views/session/home.html.erb
<article class="main">
  <%= render 'tutorials/index', :tutorials => @tutorials %>
</article>
<article class="sidebar">
  <%= render 'projects/index' %>
</article>

app/views/session/new.html.erb
<section id="signin-form">
  <% if @redirect_url %>
  <p>
    We need you to log in before we can show you the page that you are trying to
    view.
  </p>
  <% end %>
  
  <h2>Sign in</h2>
  <%= form_tag session_path do %>
  <section class="fields">
    <p class="field">
      <%= label_tag :email %>
      <span class="value">
        <%= email_field_tag :email, @email, :required => true, 
                                            :autofocus => true %>
      </span>
      <span class="comment"></span>
    </p>
    
    <p class="field">
      <%= label_tag :password %>
      <span class="value">
        <%= password_field_tag :password %>
      </span>
      <span class="comment"></span>
    </p>
  </section>
    
  <p class="actions">
    <%= submit_tag 'Sign in' %>
    
    <% if @redirect_url %>
    <%= hidden_field_tag :redirect_url, @redirect_url %>
    <% end %>
  </p>
  <% end %>
</section>

app/views/session/welcome.html.erb
<%= image_tag 'preview.png', :id => 'preview-image' %>
<article class="sidebar" id="welcome">
  <h2>
    Learn<br/>Machine Learning
  </h2>
  <p>
    ProtoM teaches you machine learning.
    It's simple and interactive so you can get down to business:
    software that understands speech, Twitter sentiment, stock prices and much, much more.
  </p>
  <div class="welcome-button">
    <%= link_to 'Learn the basics', Tutorial.by_number.first , :class => :button %>
  </div>
  <div class="welcome-button">
    <%= link_to 'Start experimenting', new_project_path, :class => :button %>
  </div>
  <div class="welcome-button">
    <h3>or</h3>
    <%= link_to 'Create account', new_user_path, :class => :button %>
    <ul class="tips">
      <li>
        <span class="ui-icon ui-icon-lightbulb"></span>
        <p>
          Start your own projects.
        </p>
      </li>
      <li>
        <span class="ui-icon ui-icon-lightbulb"></span>
        <p>
          Save trials automatically and compare your results historically.
        </p>
      </li>
      <li>
        <span class="ui-icon ui-icon-lightbulb"></span>
        <p>
          Upload your own data sets for analysis.
        </p>
      </li>
    </ul>
  </div>
</article>