config/routes.rb
Mug6470::Application.routes.draw do

  resources :tutorials, :only => [:index, :show] do
    resources :sections, :only => [:index, :show]
  end

  resources :projects do
    resources :trials
  end

  resources :trials, :only => [:destroy]

  resources :data, :except => [:destroy, :update, :edit, :new] do
    collection do
      get :choose
      get :tweet
    end
  end

  resources :classifiers, :except => [:destroy, :update, :edit, :create, :new] do 
    collection do
      get :choose
    end
  end

  resource :session, :controller => 'session' do
    collection do
      get :about
    end
  end
  
  resources :users, :only => [:new, :create] do
    collection do
      post :check_email
    end
  end
  
  match 'projects/trials' => 'trials#create'

  root :to => 'session#show'

end

app/models/user.rb
# An user account.
class User < ActiveRecord::Base
  include Authpwn::UserModel

  # Virtual email attribute, with validation.
  include Authpwn::UserExtensions::EmailField
  # Virtual password attribute, with confirmation validation.
  include Authpwn::UserExtensions::PasswordField
  # Convenience Facebook accessors.
  # include Authpwn::UserExtensions::FacebookFields


  # Add your extensions to the User class here.
  has_one :profile, :dependent => :destroy, :inverse_of => :user
  
  has_many :projects, :through => :profile
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # TODO(ushadow): Add admin.
  
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        @user.create_profile
        format.html { redirect_to new_session_path }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, :notice => 'User was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
  
  # XHR /users/check_email
  def check_email
    @email = params[:user][:email]
    @user = User.with_email @email
    
    render :layout => false
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def valid_email?(email)
    email =~ /^[A-Za-z0-9.+_]+@[^@]*\.(\w+)$/
  end

  def filter_error_msg(msg)
    if /(?<m>This e-mail address.+)|(?<m>Password.+)/ =~ msg
      m + '.'
    end
  end
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" class="ui-state-error">
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <% if msg = filter_error_msg(msg) %>
          <li><%= alert_icon_tag %><%= msg %></li>
        <% end %>
      <% end %>
      </ul>
    </div>
  <% end %>

  <section class="fields">
    <p class="field">
      <%= f.label :email %>
      <span class="value">
        <%= f.email_field :email, :required => true, :autofocus => true,
            'data-pwnfx-refresh-url' => check_email_users_url,
            'data-pwnfx-refresh-method' => 'POST',
            'data-pwnfx-refresh-target' => 'user_form_email_availability' %>
      </span>
      <span class="comment" id="user_form_email_availability"></span>
    </p>
    <p class="field">
      <%= f.label :password %>
      <span class="value">
        <%= f.password_field :password, :required => true,
            'data-pwnfx-confirm' => 'new-password' %>
      </span>
    </p>
    <p class="field">
      <%= f.label :password_confirmation %>
      <span class="value">
        <%= f.password_field :password_confirmation, :required => true,
            'data-pwnfx-confirm' => 'new-password' %>
      </span>
      <span class="comment">
        <span data-pwnfx-confirm-win="new-password" class="hidden">
          <%= ok_image_tag %>
        </span>
        <span data-pwnfx-confirm-fail="new-password" class="hidden">
          Does not match.
        </span>
    </p>
  </section>
  <p class="actions">
    <%= f.submit 'Sign up' %>
  </p>
<% end %>

app/views/users/check_email.html.erb
<% unless valid_email? @email %>
  <span class="error-text">Invalid email.</span> 
<% else %>
  <% if @user %>
    <span class="error-text">Email is taken.</span>
  <% else %>
    <%= ok_image_tag %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', user_path(@user.id) %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user_path(user.id) %></td>
    <td><%= link_to 'Edit', edit_user_path(user.id) %></td>
    <td><%= link_to 'Destroy', user_path(user.id), :confirm => 'Are you sure?', 
                    :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<section id="signup-form">
  <h2 >Sign up</h2>
  <%= render 'form' %>
</section>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user.id) %> |
<%= link_to 'Back', users_path %>