config/routes.rb
Mug6470::Application.routes.draw do

  resources :tutorials, :only => [:index, :show] do
    resources :sections, :only => [:index, :show]
  end

  resources :projects do
    resources :trials
  end

  resources :trials, :only => [:destroy]

  resources :data, :except => [:destroy, :update, :edit, :new] do
    collection do
      get :choose
      get :tweet
    end
  end

  resources :classifiers, :except => [:destroy, :update, :edit, :create, :new] do 
    collection do
      get :choose
    end
  end

  resource :session, :controller => 'session' do
    collection do
      get :about
    end
  end
  
  resources :users, :only => [:new, :create] do
    collection do
      post :check_email
    end
  end
  
  match 'projects/trials' => 'trials#create'

  root :to => 'session#show'

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :profile, :inverse_of => :projects
  validates :profile, :presence => true
  attr_protected :profile
  
  has_many :trials, :inverse_of => :project, :dependent => :destroy
  
  # Name of the project.
  validates :name, :presence => true, :length => 1..64 

  # Returns the maximum trial number in this project.
  def max_trial_number
    trials.maximum(:number) || 0
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # TODO(ushadow): handle the case when user is not logged in.
  before_filter :ensure_logged_in, :only => [:index, :create]
  
  def ensure_logged_in
    bounce_user unless current_user
  end
  private :ensure_logged_in
  
  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects || []

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new 
    
    respond_to do |format|
      if current_user
        @project.profile = current_user.profile 
        @project.name = "Project-#{current_user.projects.size + 1}"
        if @project.save
          format.html { redirect_to edit_project_url(@project), 
                                    notice: 'New project created.'}
        else
          format.html { redirect_to projects_url }
        end
      else
        format.html { render :edit }
      end
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end
  
  # TODO(ushadow): Delete unused methods.

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])
    @project.profile = current_user.profile

    respond_to do |format|
      if @project.save
        format.html { redirect_to edit_project_url(@project), 
                          notice: "#{@project.name} was successfully created." }
        format.json { render json: @project, status: :created, location: @project }
      else
        alert = @project.errors.full_messages[0] || 'Invalid project name.'
        format.html { redirect_to :back, 
                                  :alert => alert }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def close_tag
    content_tag :span, 'Delete', :class => "ui-icon ui-icon-close", 
                                 :title => "Delete"
  end

  def project_default_name
    if current_user
      "Project-#{current_user.projects.size + 1}"
    else
      ''
    end
  end
end

app/views/projects/_edit.html.erb
<article id="current-project">
  <ul id="project-nav">
    <li><a href="#current-trial">New trial</a></li>
    <%= render 'trials/index', :trials => project.trials %>
  </ul>
  <%= render 'trials/form', :trial => project.trials.build, 
                            :project => project %>
</article>

app/views/projects/_form.html.erb
<%= form_for(project) do |f| %>
  <section class="fields">
    <p class="field">
      <%= f.label :name, 'Enter a new project name:' %>
      <%= f.text_field :name, :required => true, :autofocus => true,
                       :value => project_default_name %>
   </p>
   <p class="actions">
      <%= f.submit %>
   </p>
  </section>
<% end %>

app/views/projects/_index.html.erb
<% if current_user %>
  <h2>Projects</h2>
  <%= button_tag 'New project', :id => 'new-project-button' %> 
  <%= render "projects/form", :project => Project.new %>
  <% projects = current_user.projects %>
  <% if projects.any? %>
    <ul class='projects-index'>
      <% projects.each do |project| %>
        <li>  
          <h3><%= link_to "#{project.name}", edit_project_path(project) %></h3>
          <div class="actions">
            <%= link_to close_tag, project, confirm: 'Are you sure?', method: :delete %>
          </div>
        </li>
      <% end %>
    </ul>
  <% else %>
    <ul>
      <li>
        <span class="ui-icon ui-icon-lightbulb"></span>
        <p>
          Trials in a project are saved so that
          you can come back later to compare your results.
        </p>
      </li>
      <li>
        <span class="ui-icon ui-icon-lightbulb"></span>
        <p>
          You can upload your own data sets for analysis.
        </p>
      </li>
      <li>
        <span class="ui-icon ui-icon-lightbulb"></span>
        <p>
          You can access your data and trial results wherever you go.
        </p>
      </li>
    </ul>
  <% end %>
<% else %>
  <%= link_to 'Create account', new_user_path, :class => :button %>
  <ul class="tips">
    <li>
      <span class="ui-icon ui-icon-lightbulb"></span>
      <p>
        Start your own projects.
      </p>
    </li>
    <li>
      <span class="ui-icon ui-icon-lightbulb"></span>
      <p>
        Save trials automatically and compare your results historically.
      </p>
    </li>
    <li>
      <span class="ui-icon ui-icon-lightbulb"></span>
      <p>
        Upload your own data sets for analysis.
      </p>
    </li>
  </ul>
<% end %>

app/views/projects/edit.html.erb
<%= render 'projects/edit', :project => @project %>

app/views/projects/index.html.erb
<article class='main tutorials-index'>
  <%= render 'tutorials/index', :tutorials => Tutorial.by_number %>
</article>
<article class="sidebar">
  <%= render 'projects/index', :projects => @projects %>
</article>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @project.name %>
</p>

<p>
  <b>Profile:</b>
  <%= @project.profile %>
</p>


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>