config/routes.rb
Mug6470::Application.routes.draw do

  resources :tutorials, :only => [:index, :show] do
    resources :sections, :only => [:index, :show]
  end

  resources :projects do
    resources :trials
  end

  resources :trials, :only => [:destroy]

  resources :data, :except => [:destroy, :update, :edit, :new] do
    collection do
      get :choose
      get :tweet
    end
  end

  resources :classifiers, :except => [:destroy, :update, :edit, :create, :new] do 
    collection do
      get :choose
    end
  end

  resource :session, :controller => 'session' do
    collection do
      get :about
    end
  end
  
  resources :users, :only => [:new, :create] do
    collection do
      post :check_email
    end
  end
  
  match 'projects/trials' => 'trials#create'

  root :to => 'session#show'

end

app/views/layouts/_footer.html.erb
<nav>
  <p class="copyright">
    &copy; Copyright 2012
    <a href="#">ProtoM</a>
  </p>
	<ul>
		<li>
      | <%= link_to 'About', about_session_path  %>
      | <%= link_to 'Contact', about_session_path  %>
		</li>
	</ul>	
	| <strong>Note to users:</strong> This early version of the site only works with Google Chrome.	
</nav>

app/views/layouts/_header.html.erb
<hgroup>
  <h1>
    <span class="app-name">
      <%= link_to image_tag('logo.png'), session_path %>
    </span>
  </h1>

  <%= render 'layouts/menu' %>
</hgroup>

app/views/layouts/_menu.html.erb
<nav>
  <ol>
    <% if current_user %>
      <li>
        <%= link_to current_user.email, '#' %>
      </li>
      <li>
        <%= link_to 'Tutorials', tutorials_path %>
      </li>
      <li>
        <%= link_to 'Projects', projects_path %>
      </li>
      <li>
        <%= link_to 'Sign out', session_path, :method => :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to 'Tutorials', tutorials_path %>
      </li>
      <li>
        <%= link_to 'Sign in', new_session_path %>
      </li>
      <li>
        <%= link_to 'Create account', new_user_path %>
      </li>
    <% end %>
  </ol>
</nav>

app/views/layouts/_status_bar.html.erb
<% if flash[:alert] %>
<p class="status-bar ui-state-error">
  <%= alert_icon_tag %>
  <%= flash[:alert] %>

  <span class="actions">
    <%= close_status_tag %>
  </span>
</p>
<% elsif flash[:errors] && flash[:errors].any? %>
<div class="status-bar ui-state-error">
  <%= pluralize(flash[:errors].count, "error") %> occurred:
  <span class="actions">
    <%= close_status_link %>
  </span>

  <ul>
  <% flash[:errors].full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% elsif flash[:notice] %>
<p class="status-bar ui-state-highlight">
  <%= info_icon_tag %>
  <%= flash[:notice] %>
  <span class="actions">
    <%= close_status_tag %>
  </span>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>ProtoM</title>
<%= csrf_meta_tag %>
<%= favicon_link_tag %>
<%= stylesheet_link_tag 'application' %>
<%= javascript_include_tag 'application' %>
</head>
<body>
<header>
<%= render 'layouts/header' %>
</header>

<div id="real-body">
<div id="content-wrapper">
<%= render 'layouts/status_bar' %>
<article id="main">
<%= yield %>
</article>
</div>
</div>

<footer>
<%= render 'layouts/footer' %>
</footer>
</body>
</html>

app/views/layouts/config_vars.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= config_vars_app_name %> Vars</title>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <h1><%= config_vars_app_name %> Configuration Vars</h1>
<%= yield %>
  </body>
</html>